### ISSUE TITLE
why the word embedding shape need to be multiply by 2?

### ISSUE THREAD

**Issue by xiongjun19** [aliyun/aicb#10]
I'm a little confused about the shape of word embedding in the Megatron Model? 
why the num of embedding need to multiply by two :
`  self.word_embedding = MockedParam(
            (2 * num_embedding_per_partition, hidden_size), name=self.name
        )`

**Comment by zhouheyang-alibaba** [comment]
The dimension of word_embedding is `num_embedding_per_partition * hidden_size * params_dtype` , where the value 2 indicates that the data type corresponds to 2 bytes. 
However, after carefully reading the code, I found that the data type of word_embedding is float32, which should correspond to 4 bytes. I will modify this to 4. Future versions will further support custom dtype.

**Comment by xiongjun19** [comment]
> The dimension of word_embedding is `num_embedding_per_partition * hidden_size * params_dtype` , where the value 2 indicates that the data type corresponds to 2 bytes. However, after carefully reading the code, I found that the data type of word_embedding is float32, which should correspond to 4 bytes. I will modify this to 4. Future versions will further support custom dtype.

great, I understand now, thanks for your great job

**Comment by YNG2020** [comment]
However, what should be computed here is the number of parameters (later, when calculating DP communication volume, params_dtype will be multiplied additionally), not the data size occupied by the parameters. Is this a bug?
