### ISSUE TITLE
Question about the hyper-parameters of Llama?

### ISSUE THREAD

**Issue by mama0512** [aliyun/aicb#12]
In workload/Workload_spec_v1.1.csv, I found that ffn_hidden_sizes are different from those the Llama paper mentions as below shows:
<img width="489" alt="image" src="https://github.com/user-attachments/assets/8166b025-88c7-482a-ac9d-d886288ef994">
However,in your file, I found:
<img width="742" alt="image" src="https://github.com/user-attachments/assets/94a3aa57-6200-47b6-9933-89a08f5e7b9e">
I was confused, please give me some response.

**Comment by zhouheyang-alibaba** [comment]
AICB workload suite is based on the relevant descriptions of the llama3 405B model structure found in the publicly available paper from llama. The paper can be accessed at the following link:  https://arxiv.org/pdf/2407.21783
![20241104112717](https://github.com/user-attachments/assets/c770ae0f-4b7a-4162-94f7-a5ca5cc8d526)
