### ISSUE TITLE
关于pp时能否正确反映等待时间的疑问

### ISSUE THREAD

**Issue by 191220042** [aliyun/aicb#15]
您好，我在阅读代码之后好奇，比如说在pp组中的两个rank,在broadcast时rankB需要阻塞等待rankA的输出结果，请问用workload如何正确反映这种阻塞等待的时间呢，谢谢。

**Comment by zhouheyang-alibaba** [comment]
不知道你这里是否想问的是pp组中的send/recv需要阻塞等待，这个问题要分成两点来看：
- 对于AICB物理打流来说，pp组中不同pp rank的workload是不一样的，workload会根据pp rank具体的生成isend irecv信息，运行时会实际调用torch.distributed去完成send/recv的阻塞等待。
- 对于simAI仿真来说，目前没有考虑阻塞等待的时间，认为pp通信完全被overlap掉，即将到来的版本中会进一步考虑pp通信时间

**Comment by 191220042** [comment]
谢谢，例如说在物理打流中，rankA需要计算完成才能isend，rankBirecv,但是因为没有真实的计算（没有真实的gemm），这里的计算的时间是怎么模拟的呢

**Comment by 191220042** [comment]
我的意思使rankB是需要等待rankA的计算+isend，但是rankA没有真实的计算或者sleep相应的时间，是不是会导致rankB的等待时间偏短

**Comment by 191220042** [comment]
> 我的意思使rankB是需要等待rankA的计算+isend，但是rankA没有真实的计算或者sleep相应的时间，是不是会导致rankB的等待时间偏短

**Comment by zhouheyang-alibaba** [comment]
如果你使用aicb纯通信的话，是的确实会导致rankB的等待时间偏短；
但我们有单独的aiob组件来模拟算子真实的计算时间，如果你开启了`--aiob_enable` 选项的话，会运行aiob仿真填充计算时间，在物理机上或者仿真运行时会等待那个算子的真实的计算时间的。

**Comment by 191220042** [comment]
谢谢，请问下通过aiob填充计算时间的逻辑在aicb代码库的哪个地方呢
![image](https://github.com/user-attachments/assets/1f01ab0d-3dae-4889-86a0-3bb2d5068750)
抱歉没有N卡，看代码时觉得这里好像只计算了通信的时间

**Comment by 191220042** [comment]
谢谢，请问下通过aiob填充计算时间的逻辑在aicb代码库的哪个地方呢
[ ![image](https://private-user-images.githubusercontent.com/80091648/386513537-1f01ab0d-3dae-4889-86a0-3bb2d5068750.png?](https://private-user-images.githubusercontent.com/80091648/386513537-1f01ab0d-3dae-4889-86a0-3bb2d5068750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTQxNzIsIm5iZiI6MTczMTg5Mzg3MiwicGF0aCI6Ii84MDA5MTY0OC8zODY1MTM1MzctMWYwMWFiMGQtM2RhZS00ODg5LTg2YTAtM2JiMmQ1MDY4NzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAxMzc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OWY2MDcxZWNhMTg2OTBhMGJkMmFkNTBiZDcxZTRjZjI4OWYyNDJiZjk3NWIyOWM3OTRiMTY5ZjkwOGQ0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nPklTmLfscldyjxnoE4Y3-u6YfELj0K7Fc6QQFn0AGs)
 抱歉没有N卡，看代码时觉得这里好像只计算了通信的时间

**Comment by 191220042** [comment]
> 如果你使用aicb纯通信的话，是的确实会导致rankB的等待时间偏短； 但我们有单独的aiob组件来模拟算子真实的计算时间，如果你开启了`--aiob_enable` 选项的话，会运行aiob仿真填充计算时间，在物理机上或者仿真运行时会等待那个算子的真实的计算时间的。
谢谢，请问下通过aiob填充计算时间的逻辑在aicb代码库的哪个地方呢
![386513537-1f01ab0d-3dae-4889-86a0-3bb2d5068750](https://github.com/user-attachments/assets/671a3983-57f5-49b4-80fd-42a9359f97bb)
抱歉没有N卡，看代码时觉得这里好像只计算了通信的时间

**Comment by zhouheyang-alibaba** [comment]
使能aiob之后会通过aiob计算得到一个存放算子具体计算时间文件的路径信息；
主函数中
![aicb](https://github.com/user-attachments/assets/435cf82f-5940-4176-8aaf-e815df2c0f24)
这里会将计算时间填充到Workload里，然后在处理的时候对应的commtype为computation，会进行计算时间的处理

**Comment by 191220042** [comment]
> 使能aiob之后会通过aiob计算得到一个存放算子具体计算时间文件的路径信息； 主函数中 ![aicb](https://private-user-images.githubusercontent.com/175004850/387043140-435cf82f-5940-4176-8aaf-e815df2c0f24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTk0MDQsIm5iZiI6MTczMTg5OTEwNCwicGF0aCI6Ii8xNzUwMDQ4NTAvMzg3MDQzMTQwLTQzNWNmODJmLTU5NDAtNDE3Ni04YWFmLWU4MTVkZjJjMGYyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwMzA1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDNiZDlkZjc3NTY1YmNiMGEwMzVkOGFmNTc1MGVkOGQwZTdhYjNiODFhN2ViNjViOTljZmNhZDkyMDQwY2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RgQ4BNEXwVwL-TPPKG9iPi7HSdcFuFiUALKd2Oxh3QU) 这里会将计算时间填充到Workload里，然后在处理的时候对应的commtype为computation，会进行计算时间的处理
对于pp来说，最后分析的并不是一个rank里会发生的事件而是把流水线里的行为按照时间线都刻画出来了对吗

**Comment by zhouheyang-alibaba** [comment]
> > 使能aiob之后会通过aiob计算得到一个存放算子具体计算时间文件的路径信息； 主函数中 ![aicb](https://private-user-images.githubusercontent.com/175004850/387043140-435cf82f-5940-4176-8aaf-e815df2c0f24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTk0MDQsIm5iZiI6MTczMTg5OTEwNCwicGF0aCI6Ii8xNzUwMDQ4NTAvMzg3MDQzMTQwLTQzNWNmODJmLTU5NDAtNDE3Ni04YWFmLWU4MTVkZjJjMGYyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwMzA1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDNiZDlkZjc3NTY1YmNiMGEwMzVkOGFmNTc1MGVkOGQwZTdhYjNiODFhN2ViNjViOTljZmNhZDkyMDQwY2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RgQ4BNEXwVwL-TPPKG9iPi7HSdcFuFiUALKd2Oxh3QU) 这里会将计算时间填充到Workload里，然后在处理的时候对应的commtype为computation，会进行计算时间的处理
> > 对于pp来说，最后分析的并不是一个rank里会发生的事件而是把流水线里的行为按照时间线都刻画出来了对吗

是的

**Comment by 191220042** [comment]
谢谢
