### ISSUE TITLE
日志 Log 里缺少 PP 信息，请补充功能

### ISSUE THREAD

**Issue by Huster-SC** [aliyun/aicb#16]
<img width="903" alt="截屏2024-11-14 10 13 46" src="https://github.com/user-attachments/assets/d4745c54-39ce-4cc8-b44a-45511e1b8609">

**Comment by zhouheyang-alibaba** [comment]
pp通信信息统计已在这次https://github.com/aliyun/aicb/commit/cf516c0f8a16e0c521984d1bb496f84356693dec 提交中添加
