### ISSUE TITLE
Request for the Related Paper

### ISSUE THREAD

**Issue by Manulex-Y** [aliyun/aicb#2]
Hello!
  I am a graduate student at the University of Science and Technology of China. I am part of a team working on developing CC algorithms for large-scale model training communication. We are interested in using AICB to gather communication workload data for simulation evaluation purposes.
  I noticed that there was a related paper mentioned in the project, would it be possible to acquire the PDF? If so, kindly send it to my email address: SA23218175@mail.ustc.edu.cn .
  Thank you very much for your time and consideration.

**Comment by zhouheyang-alibaba** [comment]
Thank you for your interest in our project. Our related paper, simAI, has been accepted to NSDI 2025 and will be officially published on the website in a few months, where you can download and review it. Our simAI project will also be gradually open-sourced and released in the next 1-2 months. Please continue to follow the updates on our project.
