### ISSUE TITLE
megatron通信量请教

### ISSUE THREAD

**Issue by ltm920716** [aliyun/aicb#8]
你好，
  我在双机各2卡的机器上进行了GPT-7b模型的测试，关于通信量的结果有一些疑问，来请教一下，谢谢

- 运行指令
```
NCCL_DEBUG=INFO NCCL_IB_DISABLE=0 NCCL_SOCKET_IFNAME=ens27f0 GLOO_SOCKET_IFNAME=ens27f0 NCCL_IB_HCA=mlx5_0,mlx5_1 NCCL_IB_ADAPTIVE_ROUTING=1 NCCL_IB_GID_INDEX=3 sh scripts/megatron_gpt.sh --nnodes 2 --node_rank 1 --nproc_per_node 2 --master_addr 172.28.163.141 --master_port 6001 -m 7 --world_size 4 --tensor_model_parallel_size 2 --pipeline_model_parallel 1 --frame Megatron --global_batch 8  --micro_batch 1 --seq_length 2048 --swiglu --aiob_enable
```
- dp日志结果 
![image](https://github.com/user-attachments/assets/ecd4619d-833f-4ee3-a27c-15897dae2cc3)

关于7b模型，我如上设置dp=2，tp=2，理论上每个dp组通信的数据是7GB？dp的reduce-scatter通信与all-gather通信理论上是应该一致都是7GB对么，为什么这里统计出来不一致且为2倍的关系？并且算法带宽这里为什么与通信量除以时间对不上？我本地RoCE带宽上限是12.5，为什么这里统计的总线带宽会超出实际带宽上限？

感谢指导

**Comment by Huoyuan100861** [comment]
allgather - bf16, reduce-scatter - fp32

**Comment by zhouheyang-alibaba** [comment]
感谢对于AICB如此仔细的使用：

1. 首先message size的区别就像 @Huoyuan100861 所提到的，两者使用的数据类型不同，最终的size就是不一致的；
2. 当前Busbw超过理论上限的问题可能是两方面造成的：
         2机的情况下，nccl可能会使用tree算法，此时集合通信的busbw的是可能超过理论上限的；
         当前Busbw的计算方式由于单位转换异常，确实可能稍大一点，这个问题在最新的提交中已经修改了。

**Comment by ltm920716** [comment]
感谢两位的指导，希望AICB能大大推广
